/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OMFrfkcscQN
 */
import Link from "next/link";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import Contact from "../Contact";

export function Component() {
  return (
    <>
      <div className="mx-auto max-w-[600px] space-y-7 pt-7 flex text-center items-center flex-col py-6 md:py-10 lg:py-14">
        <div className="space-y-4">
          <h1 className="text-4xl font-bold tracking-tighter md:text-6xl/relaxed">
            Send SMS messages to multiple recipients
          </h1>
          <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Upload a file with phone numbers and compose your message. We handle
            the rest.
          </p>
        </div>
        <div className="flex flex-col gap-2 w-full justify-center min-[400px]:flex-row">
          <Link
            className="inline-flex h-12 items-center justify-center rounded-md border border-gray-200 bg-gray-900 px-8 text-base font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 "
            href="/send">
            Get started
          </Link>
        </div>
      </div>
      <section
        className="py-12 md:py-24 lg:py-32"
        id="features">
        <div className="container grid items-center gap-4 px-4 text-center md:px-6 lg:gap-10">
          <div className="space-y-3 text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Features
            </h2>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              A simple and intuitive platform to send SMS messages.
            </p>
          </div>
          <div className="grid max-w-sm gap-4 mx-auto items-start sm:max-w-2xl lg:gap-6 md:grid-cols-2  xl:max-w-5xl">
            <div className="flex flex-col items-center justify-center space-y-2">
              <CheckCircleIcon className="w-12 h-12 rounded-full bg-gray-100 p-3" />
              <h3 className="font-bold">Easy to use</h3>
              <p className="text-xs text-gray-500 dark:text-gray-400">
                Intuitive interface
              </p>
            </div>
            <div className="flex flex-col items-center justify-center space-y-2">
              <CheckCircleIcon className="w-12 h-12 rounded-full bg-gray-100 p-3" />
              <h3 className="font-bold">Fast delivery</h3>
              <p className="text-xs text-gray-500 dark:text-gray-400">
                Messages sent instantly
              </p>
            </div>
            <div className="flex flex-col items-center justify-center space-y-2">
              <CheckCircleIcon className="w-12 h-12 rounded-full bg-gray-100 p-3" />
              <h3 className="font-bold">Customization</h3>
              <p className="text-xs text-gray-500 dark:text-gray-400">
                Personalize your messages
              </p>
            </div>
            <div className="flex flex-col items-center justify-center space-y-2">
              <CheckCircleIcon className="w-12 h-12 rounded-full bg-gray-100 p-3" />
              <h3 className="font-bold">Secure</h3>
              <p className="text-xs text-gray-500 dark:text-gray-400">
                Your data is safe with us
              </p>
            </div>
          </div>
        </div>
      </section>
      <section
        className="py-12 md:py-24 lg:py-32"
        id="how">
        <div className="container grid items-center gap-4 px-4 text-center md:px-6 lg:gap-10">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              How it works
            </h2>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Sending SMS messages with SMSBlaster is as easy as 1-2-3.
            </p>
          </div>
          <div className="grid max-w-sm gap-4 mx-auto items-start sm:max-w-2xl lg:gap-6 md:grid-cols-3 md:max-w-4xl">
            <div className="flex flex-col items-center justify-center space-y-2">
              <div className="flex w-12 h-12 items-center justify-center rounded-full border border-gray-200 bg-gray-900 text-gray-50 shadow transition-colors hover:translate-y-[-2px] hover:bg-gray-900/90 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-950 dark:hover:text-gray-50 dark:border-gray-800">
                1
              </div>
              <p className="text-xs text-gray-500 dark:text-gray-400">
                Upload your file
              </p>
            </div>
            <div className="flex flex-col items-center justify-center space-y-2">
              <div className="flex w-12 h-12 items-center justify-center rounded-full border border-gray-200 bg-gray-900 text-gray-50 shadow transition-colors hover:translate-y-[-2px] hover:bg-gray-900/90 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-950 dark:hover:text-gray-50 dark:border-gray-800">
                2
              </div>
              <p className="text-xs text-gray-500 dark:text-gray-400">
                Compose your message
              </p>
            </div>
            <div className="flex flex-col items-center justify-center space-y-2">
              <div className="flex w-12 h-12 items-center justify-center rounded-full border border-gray-200 bg-gray-900 text-gray-50 shadow transition-colors hover:translate-y-[-2px] hover:bg-gray-900/90 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-950 dark:hover:text-gray-50 dark:border-gray-800">
                3
              </div>
              <p className="text-xs text-gray-500 dark:text-gray-400">
                Send to recipients
              </p>
            </div>
          </div>
        </div>
      </section>
      {/* <section className="py-12 md:py-24 lg:py-32" id="testimonials">
      <div
        className="container grid items-center gap-4 px-4 text-center md:px-6 lg:gap-10">
        <div className="space-y-3 text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Trusted by our customers</h2>
          <p
            className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            We help teams of all sizes. Trusted by the best teams in the world.
          </p>
        </div>
        <div className="divide-y rounded-lg border">
          <div
            className="grid w-full grid-cols-3 items-stretch justify-center divide-x md:grid-cols-3">
            <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
              <img
                alt="Logo"
                className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                height="70"
                src="/placeholder.svg"
                width="140" />
            </div>
            <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
              <img
                alt="Logo"
                className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                height="70"
                src="/placeholder.svg"
                width="140" />
            </div>
            <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
              <img
                alt="Logo"
                className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                height="70"
                src="/placeholder.svg"
                width="140" />
            </div>
          </div>
          <div
            className="grid w-full grid-cols-3 items-stretch justify-center divide-x md:grid-cols-3">
            <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
              <img
                alt="Logo"
                className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                height="70"
                src="/placeholder.svg"
                width="140" />
            </div>
            <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
              <img
                alt="Logo"
                className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                height="70"
                src="/placeholder.svg"
                width="140" />
            </div>
            <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
              <img
                alt="Logo"
                className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                height="70"
                src="/placeholder.svg"
                width="140" />
            </div>
          </div>
        </div>
        <div className="flex flex-col gap-2 min-[400px]:flex-row justify-center">
          <Link
            className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-gray-950 px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-950/90 hover:text-gray-50 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:border-gray-800 dark:hover:bg-gray-950 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
            href="#">
            Contact Sales
          </Link>
          <Link
            className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-900 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
            href="#">
            Learn more
          </Link>
        </div>
      </div>
    </section> */}
    <Contact/>
    </>
  );
}

function CheckCircleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
      <polyline points="22 4 12 14.01 9 11.01" />
    </svg>
  );
}
