/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YMEy4ikAwlY
 */
import Link from "next/link";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export function Component() {
  return (
    <>
      <div className="mx-auto max-w-[600px] h-screen space-y-7 pt-10 flex text-center items-center flex-col md:py-10 lg:py-14">
        <div className="space-y-3 text-center md:space-y-5 lg:text-left lg:grid lg:gap-10 lg:space-y-0">
          <div className="space-y-2 text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Upload your file
            </h2>
            <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Upload a CSV file with phone numbers and start composing your
              message.
            </p>
          </div>
          <div className="mx-auto space-y-4 lg:w-full lg:mx-0 lg:space-y-5 items-center">
            <form className="space-y-4 px-4">
              <div className="flex flex-col gap-5 w-full">
                <Label
                  className="text-base"
                  htmlFor="file">
                  Upload your file
                </Label>
                <Input
                  id="file"
                  placeholder="Upload your file"
                  type="file"
                />
                <div />
              </div>
              <div className="flex flex-col gap-2">
                <Label
                  className="text-base"
                  htmlFor="message">
                  Enter your message
                </Label>
                <Textarea
                  id="message"
                  placeholder="Enter your message..."
                />
              </div>
              <Button type="submit">Send Messages</Button>
            </form>
          </div>
        </div>
      </div>
    </>
  );
}
